### ISSUE TITLE
Grid Bug

### ISSUE THREAD

**Issue by Plasmoner** [Plasmoner/All-things-plasma#1]
**Neon User 5.9.5**
![01](https://cloud.githubusercontent.com/assets/29124716/26684981/6d1eeb30-46f1-11e7-94a7-8b20750f0310.png)

**After updating to 5.10.0**
![02](https://cloud.githubusercontent.com/assets/29124716/26685195/10ee07c8-46f2-11e7-9b50-e7fa1dd20182.png)

In spite of my best try, it just won't stick to where I drag it. Both "Home" and "Trash" are off.
![03](https://cloud.githubusercontent.com/assets/29124716/26685414/c2e8d372-46f2-11e7-824d-7ba39bad9dec.png)

Replicated the issue several times. Probably a bug.

**Comment by Plasmoner** [comment]
Notice the overlap
![04](https://cloud.githubusercontent.com/assets/29124716/26690427/edf132a8-4701-11e7-9bd4-2092ee893dec.png)

**Comment by Plasmoner** [comment]
Mind explaining the gap at the right, where the pointer is?
![05](https://cloud.githubusercontent.com/assets/29124716/26697683/9012e64e-471b-11e7-8327-0ddb5ca14454.png)

**Comment by Plasmoner** [comment]
@BigDaddyonTech You seem like a seasoned KDE user to me. Please have a look. The thread is visible from the forum as well as from bugs.kde.org.

**Comment by Plasmoner** [comment]
Seems the grid has shifted to the left for whatever reason. @Zren What do you think?

**Comment by Zren** [comment]
I don't believe it uses dynamic spacing. You'd have to edit the QML, and I don't think it would be a simple change either.

**Comment by Zren** [comment]
You might be interested in this which highlights a bunch of config tips.

https://zren.github.io/projects/kde/#configuration

**Comment by Plasmoner** [comment]
@Zren Thanks. Still, in 5.9.5 the grid was positioned just fine. In 5.10.0 the grid is shifted to the left. I'm posting two more and then it's out of my hands. Have done what I could.
***
@MichaelTunnell Last but not least. Please consult the thread and tell me your opinion. I understand you might not keep things on the Desktop but still.

![06](https://cloud.githubusercontent.com/assets/29124716/26702554/326ea3ee-472e-11e7-9c84-eaf4c317f2f4.png)
![07](https://cloud.githubusercontent.com/assets/29124716/26702560/3b718722-472e-11e7-9714-856cc4dabc0e.png)

Thanks guys!

**Comment by Plasmoner** [comment]
@jriddell Terribly sorry for disturbing you. But what's your opinion on the matter? If I wouldn't love Neon then I wouldn't care at all. The thing is I love it. It's second to none.

**Comment by Plasmoner** [comment]
My first clumsy attempt. I'm not even sure whether it's done right. Exercise makes perfect.
https://bugs.kde.org/show_bug.cgi?id=380424

**Comment by Zren** [comment]
Maybe it was done here? https://github.com/KDE/plasma-desktop/commit/8422f020cb1e130385f7e2ffdd73c77331d00b79

Iunno. I need to update to v5.10 soon.

**Comment by MichaelTunnell** [comment]
that's very weird and looks like a bug. As I have said in the past, random github repos are not a good place for discussing bugs. Please stick to the official bug reporting platforms supported by the specific projects. I know you are using the bugs.kde.org and that is good but you need to keep using. Also upload screenshots individually not as zip files.

**Comment by Plasmoner** [comment]
KDE/plasma-desktop@8422f02
https://bugs.kde.org/show_bug.cgi?id=380424

@MichaelTunnell Seems it's not a bug. It's by design. I'll thinker about it.

**Comment by Plasmoner** [comment]
@Zren @MichaelTunnell 

> The gap isn't a new thing - different screen resolutions can fit a number of icon columns more or less neatly. There's currently no attempt made to adjust the grid spacing to the screen resolution.

I'm on a 1920 x 1080. Out of luck, I guess. I rest my case.

**Comment by Plasmoner** [comment]
PS: I'm considering a new monitor to adapt to the grid. What resolution would be suitable, I wonder. Just kidding. At least I now know it's not a bug and I've got the hang of how to report them. Obviously, I'm confident there will not be much to report.

**Comment by Plasmoner** [comment]
@MichaelTunnell @Zren @BigDaddyonTech I realize the issue might not be all that important for some. Nonetheless, since all 4 of us (as well as others) are in interested in all things plasma, you might wanna check the dynamics of the issue  https://bugs.kde.org/show_bug.cgi?id=380424 once in a while.

**Comment by Zren** [comment]
Today is when the bugfixing plasma 5.10.1 is released. I remeber seeing a patch on phab that would add dynamic spacing based on the leftover pixels but i never tested it. So wait for the update basically.

**Comment by Zren** [comment]
Hum, maybe I'm crazy and imagined the bugfix, as I don't see it in [the changelog](https://www.kde.org/announcements/plasma-5.10.0-5.10.1-changelog.php) or on [phab](https://phabricator.kde.org/differential/query/7LklMmkHDcva/#R). This is gonna drive me crazy trying to figure out where I thought I saw it.

**Comment by Plasmoner** [comment]
@Zren Nah. Just relax. No reason to go nuts over it. Just reinstalled from the latest image and I'm impressed. Seems Neon is getting better n better. It's still 5.10.0 though and it still has the issue but other than that everything went smoothly. Truth to tell, the nicest desktop I've ever seen on top of GNU with a Linux kernel. It's a thing of beauty.

**Comment by MichaelTunnell** [comment]
I dont consider this much of a problem since the Desktop Toolbox is completely worthless in my opinion. It doesn't provide anything that right clicking the desktop doesn't provide so I just disable the toolbox on all monitors for all of my systems because it is not useful. This eliminates the issue entirely.

**Comment by Plasmoner** [comment]
Workarounds are workarounds. I still think the issue should be addressed and solved. That well-know proprietary OS seems to had dealt with it more than a decade ago. I don't see any reason why we couldn't do the same. My reference to that OS is purely technical.

> I don't consider this much of a problem since the Desktop Toolbox is completely worthless in my opinion

Agreed. Nonetheless, since the Desktop Toolbox is part of the desktop as well as other elements that might or might not be useful, everything should blend perfectly.

**Comment by Plasmoner** [comment]
_Me not using an element or several doesn't mean those are unimportant. If those are part of the desktop, irrelevant of whether I use them or disable them, they should be in perfect working condition, as plasma is not for me only._

**Comment by Plasmoner** [comment]
Just updated to 5.10.1. Everything went smoothly and the desktop feels n behaves right. The grid is still what it was. Without the Desktop Toolbox ... 
![screenshot_20170607_181652](https://user-images.githubusercontent.com/29124716/26886690-b5e3d2a6-4bae-11e7-9595-370703391564.png)

**Comment by Plasmoner** [comment]
I wonder what that "Target Milestone: 1.0" right there https://bugs.kde.org/show_bug.cgi?id=380424 means?

At any rate, I can't complain much. A dynamic grid would be nice though. As good as it gets for now and it's pretty good.

**Comment by Plasmoner** [comment]
![screenshot_20170607_212223](https://user-images.githubusercontent.com/29124716/26894575-75041624-4bc7-11e7-9123-9537bc59c9b5.png)

**Comment by Plasmoner** [comment]
@MichaelTunnell I'm keeping the toolbox. One of the things I like about Plasma is it gives you choice. Like doing the same in a million different ways? :)

**Comment by Plasmoner** [comment]
![screenshot_20170607_221714](https://user-images.githubusercontent.com/29124716/26896900-25ba1598-4bcf-11e7-86eb-19999948020f.png)

**Comment by Plasmoner** [comment]
Hmmmm

**Comment by Plasmoner** [comment]
@cfeck Thanks.

**Comment by Plasmoner** [comment]
![screenshot_20170607_231450](https://user-images.githubusercontent.com/29124716/26899565-2a987c90-4bd8-11e7-9c34-20afe6022145.png)

This thing is powerful.

**Comment by Plasmoner** [comment]
@Zren I think it's a hot corner there that is too close to the home folder (can make one miss the folder view arrow)

![screenshot_20170607_232721](https://user-images.githubusercontent.com/29124716/26899923-545d1332-4bd9-11e7-8748-e6618fc8ac60.png)

**Comment by Zren** [comment]
... so? Put the folder elsewhere if that's your jam. Or move the hot corner. If it's in the top right it'll conflict with a top right hot corner (once spacing is fixed).

**Comment by Plasmoner** [comment]
I thought any conflict is made impossible by design. Alright.

**Comment by Plasmoner** [comment]
Yep. It's definitely a powerful desktop. Way more powerful than I initially thought. And pretty. And quite stable. Maybe just me but feels snappier than before. The memory footprint seems to have dropped too but I'm not sure. The current wallpaper looks like a waterfall. Interesting. The content and the form are equally important in an OS. It seems to have achieved that balance and it'll probably get even better. So yeah, it rocks.

**Comment by Plasmoner** [comment]
Alright.

**Comment by Plasmoner** [comment]
https://phabricator.kde.org/D4856

**Comment by Plasmoner** [comment]
https://phabricator.kde.org/D4856

Making the folder view item delegates tighter was a good thing. The only thing I wish for is resolution-based auto-adaptability. As in that well-know OS (purely technical reference). I rest my case.

**Comment by Plasmoner** [comment]
https://phabricator.kde.org/D4856

Making the folder view item delegates tighter was a good thing. The only thing I wish for is resolution-based auto-adaptability and auto conflict mitigation in conjunction with the Desktop Toolbox and hot corners.

**Comment by Plasmoner** [comment]
***

**Comment by Plasmoner** [comment]
@Zren I'm notoriously easy to please :)

**Comment by MichaelTunnell** [comment]
Please, stop pinging me on GitHub for support. I've asked this of you previously and please don't continue doing it. Every project has their preferred method of support, use that not some random personal github repo, that's not what GitHub is for.

All of the following pinged me and none of these threads even exist anymore:
[[Plasmoner/Time] Router time (#1)](https://github.com/Plasmoner/Time/issues/1)
[[Plasmoner/ipfire] Opinions (#1)](https://github.com/Plasmoner/ipfire/issues/1)
[[Plasmoner/tty1] How to handle tty (#1)](https://github.com/Plasmoner/tty1/issues/1)
[[Plasmoner/Full-update] Essential Commands (#1)](https://github.com/Plasmoner/Full-update/issues/1)

Please stop pinging me on GitHub for random issues and use the proper channels if you want people to help.

**Comment by Plasmoner** [comment]
Plasma 5.10.95

![screenshot_20171011_202940](https://user-images.githubusercontent.com/29124716/31523120-5f570bd6-afba-11e7-90a7-54b725de5fc8.png)
![screenshot_20171011_203014](https://user-images.githubusercontent.com/29124716/31523125-6b61bce6-afba-11e7-830f-9588b36678c1.png)
![screenshot_20171011_203054](https://user-images.githubusercontent.com/29124716/31523141-850e4880-afba-11e7-90d3-4e610ce93167.png)
![screenshot_20171011_204933](https://user-images.githubusercontent.com/29124716/31523153-94016f70-afba-11e7-9847-449f877b66f4.png)

@Zren 
@MichaelTunnell 

Hot! No more gap at the right of the screen.
